### ISSUE TITLE
Question: disable capitalization of text values

### ISSUE THREAD

**Issue by JeffWinder** [vinz3872/vuejs-tree#33]
I'm not sure if it's by design or a bug but the first character of ever word gets capitalized when the tree is rendered.
For example, when in the codesandbox example - in the `treeDisplayData` object -  I change

`text: "Root 1" `
to
`text: "Root 1 test" `
it renders as "Root 1 Test" 

Can I disable this behavior?

**Comment by JeffWinder** [comment]
Answering my own question, I did this by adding this to my global scss file:
span.capitalize {
```
  text-transform: none !important;
}
```
But  you'd need to be more specific with your selector if you have other span elements that use  text-transform.

**Comment by vinz3872** [comment]
Hi,
Indeed, that something that could be set in the customOptions. I'll change this soon :slightly_smiling_face:

**Comment by vinz3872** [comment]
Hi, sorry it took longer that expected, but the new version is out https://github.com/scalia/vuejs-tree/tree/2.1.0 :slightly_smiling_face: 

You can change the text class with the customStyles option (the key is in `text.class`)
