### ISSUE TITLE
How to style the active row ? 

### ISSUE THREAD

**Issue by lk77** [vinz3872/vuejs-tree#35]
Hello,

i want to style the active row, 
but this does not seems to be possible

```
customStyles: {
          row: {
              background: '#eee',
              active: {
                  background: '#ccc'
              }
          },
}
```

i can style the background of the text, but not the entire row,
i could add a style for the .row_data but there is no .active class on it

thanks.

edit:

i found a way to do it :

```
onSelected(node) {
            this.$refs.tree.selectNode(node.id);
            this.$el.querySelectorAll('.selected-node').forEach(el => {
                el.classList.remove('selected-node');
            });
            this.$el.querySelector('.node[data-id="' + node.id + '"]').classList.add('selected-node');
        }
```

**Comment by vinz3872** [comment]
Hi, it will be possible in the next versions which will be released soon :slightly_smiling_face:   
(with `customStyles.row.child.style and customStyles.row.child.active.style`)

**Comment by lk77** [comment]
thanks !

**Comment by vinz3872** [comment]
Hi, sorry it took longer that expected, but the new version is out https://github.com/scalia/vuejs-tree/tree/2.1.0 :slightly_smiling_face: 

Now you can change the style with `customStyles.row.child.style` and `customStyles.row.child.active.style`

**Comment by lk77** [comment]
thanks ! i will use that instead of my little hack
