### ISSUE TITLE
Can parent be deselected when 1 of all selected children is deselected?

### ISSUE THREAD

**Issue by nickbien** [vinz3872/vuejs-tree#38]
Say parent has been selected, this will select every child it has. Currently when user deselect one from the children, parent is still selected which should be deselected after deselecting 1 child.
May I ask if there is already a function call to do it? Thanks!

Sample: [https://imgur.com/a/0DVZFgE](https://imgur.com/a/0DVZFgE)

**Comment by vinz3872** [comment]
Hi, right now it's not possible with the default behavior.
But you can overwrite this by passing a function pointer via the customOptions param like this: 
```js
// customOption param
customOption: {
  events: {
    checked: {
      state: true,
      fn: myFunction // function pointer that will overwrite the default 'checked' behavior
    }
  }
}

myFunction(node) {}
```

**Comment by ThaDaVos** [comment]
I tried doing the above as I am wondering the same but it seems calling the `checkNode` and `uncheckNode` methods also change the states of their children... not only of the chosen node - setting `node.state.checked` manually doesn't update the the UI...

So is there any way to uncheck or check a node without changing it's children states?

(I am using the Vue2 version of the package and it seems to be coming from the following two pieces of code in `TreeRow.vue`, `depth` seems to be fully ignored here...)
![image](https://user-images.githubusercontent.com/5251028/127358176-60edc55e-e05a-4bf5-b880-0feca14e0737.png)

**Comment by ThaDaVos** [comment]
My code implementation of the checked function:
![image](https://user-images.githubusercontent.com/5251028/127358259-f43592be-c9dc-4e7c-8c24-511d63dccba6.png)

**Comment by vinz3872** [comment]
Hi,
The `depth` argument is only used to help finding the node when you have multiple nodes with the same id

With the 2.x version, you can use the `forceRender` tree function that will force the refresh. It take all the nodes as it's first param. So you can use something like this:
```js
// edit one node
tree.findNode(node.id).state.checked = state
// or multiple nodes
let path = tree.findNodePath(node.id)
path.pop()
path.forEach((nodeId) => {
  tree.findNode(nodeId).state.checked = state
})

// then refresh the tree
tree.forceRender(allNodes)
```

If possible, you could use the 3.x version (but it uses Vue3). With this, you can manually change `node.state.checked` (because the updates are better handled by vue3) and no need to re-render the tree.
