### ISSUE TITLE
Is it working for vue 3 ?

### ISSUE THREAD

**Issue by LoicMoerman** [vinz3872/vuejs-tree#46]
Hello, is the latest version functional on Vue 3? I don't feel like the sandbox is working

Thanks

**Comment by lk77** [comment]
Hello,

it's working for me but visually broken

**Comment by vinz3872** [comment]
Hi
It works with the vuejs 3 version, there was indeed an error with the sandbox's example but it's fixed now

**Comment by LoicMoerman** [comment]
Sorry but right now when I try to add a raw in the sandbox example i got this error : 

![image](https://user-images.githubusercontent.com/33154363/155896530-8c1ddbec-e171-495d-b49c-0a277bbba051.png)

**Comment by vinz3872** [comment]
Indeed, i didn't update the "addNode" function in the example.
Thanks, it's fixed now 😃
