### ISSUE TITLE
getCheckedNodes returns empty array

### ISSUE THREAD

**Issue by jflash49** [vinz3872/vuejs-tree#59]
Hi,

I am trying to populate a tree dynamically. My API sends data to a function that structures the tree and pass it to the vuejs-tree component. Getting an individual node id/text works fine but the getCheckedNodes always returns an empty list. Not sure what i'm missing.

**Comment by vinz3872** [comment]
Hello, getCheckedNodes function have two parameters, the first one is to select what data you want to return.
for example you'll need to do this `this.tree.getCheckedNodes("id")` or `this.tree.getCheckedNodes(["id", "text"])` :slightly_smiling_face:
